# Name of the GitHub Action
name: Generate Snake Animation

# Controls when the action will run
on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The job that will generate the snake animation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This is the part you provided
      - uses: platane/snk@v3
        with:
          # Your GitHub username is fetched automatically
          github_user_name: ${{ github.repository_owner }}
          
          # Here we are generating multiple files
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # This step will commit the generated files to the repository
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          # The branch the action should deploy to.
          target_branch: output
          # The folder the action should deploy.
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
